# Generated by Django 3.1.4 on 2021-01-07 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients2', '0001_initial'),
        ('products2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='Date')),
                ('payment_method', models.CharField(max_length=60, null=True, verbose_name='Payment Method')),
                ('delivery_method', models.CharField(max_length=60, null=True, verbose_name='Delivery Method')),
                ('delivery_date', models.DateTimeField(verbose_name='Delivery Date')),
                ('total_price', models.FloatField(verbose_name='Total Price')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients2.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='Date')),
                ('item_price', models.FloatField(null=True, verbose_name='Item Price')),
                ('product_quantity', models.IntegerField(null=True, verbose_name='Product Quantity')),
                ('sub_total', models.FloatField(null=True, verbose_name='Sub Total Price')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders2.order', verbose_name='Order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products2.product', verbose_name='Good')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'carts',
            },
        ),
    ]
