# Generated by Django 3.1.4 on 2021-01-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=60, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=60, verbose_name='Email')),
                ('address', models.CharField(max_length=40, null=True, verbose_name='Address')),
                ('city', models.CharField(max_length=40, null=True, verbose_name='City')),
                ('province', models.CharField(max_length=40, null=True, verbose_name='Province')),
                ('country', models.CharField(max_length=40, null=True, verbose_name='Country')),
                ('postal_code', models.CharField(max_length=40, null=True, verbose_name='Postal Code')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
            },
        ),
    ]
